import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Marquee from "@/component/Marquee";
import Footer from "@/component/Footer";

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin", "bengali"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Bazar Dor",
  description: "Generated by Poran Mia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn" 
    data-theme="light"
    className={`${hindSiliguri.className} h-full antialiased`}>
      <body className= "min-h-full flex flex-col bg-[#F0F5F0]">
        <Header ></Header>
        <Marquee></Marquee>
        <main className="flex-1">
          {children}
        </main>
        {/* <h1>আজকের দাম</h1> */}
        <Footer></Footer>
      </body>
    </html>
  );
}