import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Marquee from "@/component/Marquee";
import Footer from "@/component/Footer";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin", "bengali"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Bazar Dor",
  description: "Generated by Poran Mia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn" 

    data-theme="light"
    className={`${hindSiliguri.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
  <Suspense fallback={<div className="h-16" />}>
    <Header />
  </Suspense>

  <Suspense fallback={<div className="h-10" />}>
    <Marquee />
  </Suspense>

  <main className="flex-1">
    {children}
    <Toaster position="top-right" />
  </main>

  <Suspense fallback={null}>
    <Footer />
  </Suspense>
</body>
    </html>
  );
}